{
    "name": "se-general-template",
    "description": "General project template based on Grunt/Gulp task runners",
    "devDependencies": {
        "autoprefixer": "^6.5.0",
        "babel-preset-es2015": "^6.22.0",
        "babel-preset-es2015-rollup": "^3.0.0",
        "browser-sync": "^2.17.0",
        "del": "^2.2.2",
        "gulp": "^3.9.1",
        "gulp-babel": "^6.1.2",
        "gulp-changed": "^1.3.2",
        "gulp-coffee": "^2.3.2",
        "gulp-data": "^1.2.1",
        "gulp-htmlmin": "^3.0.0",
        "gulp-imagemin": "^3.0.3",
        "gulp-merge-media-queries": "^0.2.1",
        "gulp-plumber": "^1.1.0",
        "gulp-postcss": "^6.2.0",
        "gulp-pug": "^3.0.4",
        "gulp-rename": "^1.2.2",
        "gulp-rigger": "^0.5.8",
        "gulp-rollup": "^2.11.0",
        "gulp-sass": "^2.3.2",
        "gulp-stylus": "^2.5.0",
        "gulp-uglify": "^2.0.0",
        "gulp-watch": "^4.3.10",
        "gulp.spritesmith": "^6.2.1",
        "merge-stream": "^1.0.0",
        "postcss-csso": "^1.1.2",
        "require-dir": "^0.3.0",
        "rollup-plugin-babel": "^2.7.1",
        "run-sequence": "^1.2.2",
        "vinyl-paths": "^2.1.0"
    },
    "dependencies": {}
}
